import {coverageGaps} from './document-model.mjs';
import {renderText} from './math.mjs';

export const escape = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'}[char]));
export const copy = {
  fr: {copyDiagram:'Copier le diagramme en image', imagePending:'Création de l’image…', imageCopied:'Image copiée dans le presse-papiers.', imageDownloaded:'Presse-papiers indisponible : image PNG téléchargée.', imageFailed:'Impossible de créer l’image.', overview:'Vue d’ensemble', requirements:'Exigences', constraints:'Contraintes', taskCount:'tâches', tasks:'Plan de livraison', checks:'Vérification', seeds:'Données de test', risks:'Points de vigilance', entries:'Plan technique', goals:'Objectifs', users:'Utilisateurs', outOfScope:'Hors périmètre', successMetrics:'Signaux de réussite', preDraft:'Repérage préalable', code:'Développement', 'human-qa':'Recette humaine', functional:'Fonctionnel', 'non-functional':'Non fonctionnel', must:'Indispensable', should:'Souhaitable', could:'Optionnel', acceptance:'Critères d’acceptation', dependsOn:'Dépend de', scope:'Périmètre d’écriture', forbiddenScope:'Surfaces exclues', validation:'Vérifications prévues', steps:'Étapes', expected:'Résultat attendu', cleanup:'Nettoyage', setup:'Préparation', safety:'Protection', planned:'Prévu', passed:'Réussi', failed:'Échec', blocked:'Bloqué', implemented:'Implémenté', validated:'Validé', simplified:'Simplifié', revalidated:'Revalidé', reviewed:'Revu', 'ready-to-open':'Prêt à livrer', 'delivered-local':'Livré localement', published:'PR/MR ouverte', accepted:'Accepté', automated:'Automatisé', runtime:'Exécution', manual:'Manuel', none:'Aucune', search:'Rechercher dans le document', print:'Imprimer', theme:'Thème sombre', import:'Importer un JSON', export:'Exporter le JSON', expand:'Tout développer', collapse:'Tout replier', revision:'Révision', draft:'Validation en attente', approved:'PRD approuvé', source:'Document de travail', noResults:'Aucun résultat.', found:'élément(s) trouvé(s)', noEvidence:'Aucun résultat enregistré. Les vérifications ci-dessous sont prévues.', evidence:'Preuve enregistrée', linkedTasks:'Tâches associées', planRefs:'Références techniques', global:'Transversal', current:'État actuel', reuse:'Réutilisation', boundary:'Frontières', contract:'Contrats', decision:'Décisions', calculation:'Calculs et règles', flow:'Flux', rollout:'Déploiement', risk:'Risque', assumption:'Hypothèse', question:'Question', open:'Ouvert', resolved:'Résolu', alternative:'Alternative', consequences:'Conséquences', example:'Exemple', diagramSource:'Source du diagramme', sourceOnly:'Diagramme présenté en source, non compilé. Utiliser la commande render pour produire le SVG.', approvals:'Approbations', digest:'Empreinte du document', graph:'Dépendances des tâches', emptyTasks:'Aucune tâche définie.', coverage:'Couverture à compléter', plan:'Architecture de référence', imported:'JSON importé. Les résultats de l’ancien document ne sont pas repris.', skip:'Aller au contenu', nav:'Sommaire', dependencyOrder:'Ordre de dépendance'},
  en: {copyDiagram:'Copy diagram as image', imagePending:'Creating image…', imageCopied:'Image copied to clipboard.', imageDownloaded:'Clipboard unavailable: PNG image downloaded.', imageFailed:'Could not create image.', overview:'Overview', requirements:'Requirements', constraints:'Constraints', taskCount:'tasks', tasks:'Delivery plan', checks:'Verification', seeds:'Test data', risks:'Points to resolve', entries:'Technical plan', goals:'Goals', users:'Users', outOfScope:'Out of scope', successMetrics:'Success signals', preDraft:'Pre-draft findings', code:'Development', 'human-qa':'Human acceptance', functional:'Functional', 'non-functional':'Non-functional', must:'Must', should:'Should', could:'Could', acceptance:'Acceptance criteria', dependsOn:'Depends on', scope:'Write scope', forbiddenScope:'Excluded surfaces', validation:'Planned checks', steps:'Steps', expected:'Expected result', cleanup:'Cleanup', setup:'Setup', safety:'Safety guard', planned:'Planned', passed:'Passed', failed:'Failed', blocked:'Blocked', implemented:'Implemented', validated:'Validated', simplified:'Simplified', revalidated:'Revalidated', reviewed:'Reviewed', 'ready-to-open':'Ready for delivery', 'delivered-local':'Delivered locally', published:'PR/MR opened', accepted:'Accepted', automated:'Automated', runtime:'Runtime', manual:'Manual', none:'None', search:'Search this document', print:'Print', theme:'Dark theme', import:'Import JSON', export:'Export JSON', expand:'Expand all', collapse:'Collapse all', revision:'Revision', draft:'Approval pending', approved:'PRD approved', source:'Working document', noResults:'No results.', found:'matching item(s)', noEvidence:'No results recorded. The checks below are planned.', evidence:'Recorded evidence', linkedTasks:'Related tasks', planRefs:'Technical references', global:'Cross-cutting', current:'Current state', reuse:'Reuse', boundary:'Boundaries', contract:'Contracts', decision:'Decisions', calculation:'Calculations and rules', flow:'Flows', rollout:'Rollout', risk:'Risk', assumption:'Assumption', question:'Question', open:'Open', resolved:'Resolved', alternative:'Alternative', consequences:'Consequences', example:'Example', diagramSource:'Diagram source', sourceOnly:'Diagram shown as source, not compiled. Use the render command to produce SVG.', approvals:'Approvals', digest:'Document fingerprint', graph:'Task dependencies', emptyTasks:'No tasks defined.', coverage:'Incomplete coverage', plan:'Reference architecture', imported:'JSON imported. Previous execution evidence was not carried over.', skip:'Skip to content', nav:'Contents', dependencyOrder:'Dependency order'}
};

const prose = text => `<p class="prose">${renderText(text)}</p>`;
const list = items => `<ul>${items.map(text => `<li>${renderText(text)}</li>`).join('')}</ul>`;
const links = ids => ids.map(id => `<a class="ref" href="#item-${escape(id)}">${escape(id)}</a>`).join(' ');
const badge = (value, t) => `<span class="badge ${['passed','accepted','published','delivered-local'].includes(value) ? 'good' : value === 'failed' ? 'bad' : ''}">${escape(t[value] || value)}</span>`;
const field = (key, value, t) => !value?.length ? '' : `<div class="field"><p class="field-label">${escape(t[key] || key)}</p>${Array.isArray(value) ? list(value) : prose(value)}</div>`;

function dependencyGraph(tasks, t) {
  if (!tasks.length) return '';
  const levels = new Map();
  function level(task) {
    if (levels.has(task.id)) return levels.get(task.id);
    const value = task.dependsOn.length ? 1 + Math.max(...task.dependsOn.map(id => level(tasks.find(item => item.id === id)))) : 0;
    levels.set(task.id, value); return value;
  }
  tasks.forEach(level);
  const groups = [];
  for (const task of tasks) (groups[levels.get(task.id)] ||= []).push(task);
  return `<div class="dependency-map" aria-label="${escape(t.graph)}">${groups.map((group, index) => `<div class="dependency-stage"><span class="eyebrow">${String(index + 1).padStart(2, '0')}</span>${group.map(task => `<a href="#item-${escape(task.id)}"><span class="mono">${escape(task.id)}</span><span>${escape(task.title)}</span></a>`).join('')}</div>`).join('')}</div>`;
}

export function renderDocument(payload) {
  const {document: doc, execution: state, diagrams = {}, linkedPlan} = payload;
  const t = copy[doc.locale];
  const sections = [];
  function section(id, title, content, subtitle = '') {
    if (content) sections.push({id, title, html: `<section id="section-${id}" class="document-section"><header class="section-heading"><span class="section-number">${String(sections.length + 1).padStart(2, '0')}</span><div><h2>${escape(title)}</h2>${subtitle ? `<p class="section-caption">${escape(subtitle)}</p>` : ''}</div></header>${content}</section>`});
  }
  let overview = ['goals','users','outOfScope','successMetrics'].map(key => field(key, doc[key], t)).join('');
  if (doc.preDraft) overview += `<details><summary>${t.preDraft}</summary>${Object.entries(doc.preDraft).map(([key, value]) => field(key, value, t)).join('')}</details>`;
  if (doc.techPlan) overview += `<div class="reference-plan"><span class="eyebrow">${t.plan}</span><p>${escape(doc.techPlan.id)} · ${t.revision} ${escape(doc.techPlan.revision)}${linkedPlan ? ` <a href="${escape(linkedPlan)}" aria-label="${t.plan}">↗</a>` : ''}</p></div>`;
  section('overview', t.overview, overview);
  section('constraints', t.constraints, doc.constraints.length ? `<ol class="constraints">${doc.constraints.map(text => `<li>${renderText(text)}</li>`).join('')}</ol>` : '');
  if (doc.kind === 'prd') {
    section('requirements', t.requirements, doc.requirements.map(req => `<article id="item-${escape(req.id)}" class="requirement searchable"><div class="item-top"><span class="mono">${escape(req.id)}</span>${badge(req.priority,t)}<span class="muted">${t[req.kind]}</span></div><h3>${escape(req.title)}</h3>${prose(req.description)}${field('acceptance', req.acceptance,t)}<div class="item-links"><span>${t.linkedTasks}</span>${links(doc.tasks.filter(task => task.requirementIds.includes(req.id)).map(task => task.id))}</div></article>`).join(''));
    const taskRows = doc.tasks.map(task => {
      const result = state?.tasks[task.id];
      return `<details id="item-${escape(task.id)}" class="task searchable"><summary><span class="mono">${escape(task.id)}</span><span class="task-title">${escape(task.title)}<small>${t[task.kind]}</small></span>${badge(result?.phase || 'planned',t)}</summary><div class="task-body">${task.goal ? prose(task.goal) : ''}<div class="item-links"><span>${t.requirements}</span>${links(task.requirementIds)}</div><div class="item-links"><span>${t.dependsOn}</span>${task.dependsOn.length ? links(task.dependsOn) : t.none}</div>${['scope','forbiddenScope','validation','steps','expected','cleanup'].map(key => field(key,task[key],t)).join('')}${task.seedIds.length ? `<div class="item-links"><span>${t.seeds}</span>${links(task.seedIds)}</div>` : ''}${task.planRefs.length ? `<div class="item-links"><span>${t.planRefs}</span>${task.planRefs.map(id => linkedPlan ? `<a class="ref" href="${escape(linkedPlan)}#item-${escape(id)}">${escape(id)}</a>` : `<code>${escape(id)}</code>`).join(' ')}</div>` : ''}${result ? field('evidence',result.evidence,t) : ''}${result?.pr ? `<a href="${escape(result.pr)}" rel="noreferrer">Pull request ↗</a>` : ''}</div></details>`;
    }).join('');
    section('tasks',t.tasks,dependencyGraph(doc.tasks,t) + (taskRows || prose(t.emptyTasks)));
    section('checks',t.checks,(!state || !Object.keys(state.checks).length ? `<p class="notice">${t.noEvidence}</p>` : '') + doc.checks.map(check => {
      const result=state?.checks[check.id];
      return `<article id="item-${escape(check.id)}" class="check searchable"><div class="item-top"><span class="mono">${escape(check.id)}</span>${badge(result?.result || 'planned',t)}<span class="muted">${t[check.route]}</span></div><h3>${escape(check.scenario)}</h3><div class="item-links">${links(check.requirementIds)} ${links(check.seedIds)}</div>${field('expected',check.expected,t)}${field('risk',check.risk,t)}${result ? field('evidence',result.evidence,t) : ''}</article>`;
    }).join(''));
    section('seeds',t.seeds,doc.seeds.map(seed => `<details id="item-${escape(seed.id)}" class="searchable"><summary><span class="mono">${escape(seed.id)}</span> ${escape(seed.description)}</summary><div class="task-body">${['setup','cleanup','safety'].map(key=>field(key,seed[key],t)).join('')}${links(seed.requirementIds)}</div></details>`).join(''));
    section('risks',t.risks,doc.risks.map(risk=>`<article id="item-${escape(risk.id)}" class="risk searchable"><div class="item-top"><span class="mono">${escape(risk.id)}</span>${badge(risk.status,t)}<span>${t[risk.kind]}</span></div>${prose(risk.description)}${risk.mitigation ? prose(risk.mitigation) : ''}${risk.owner ? `<p class="muted">${escape(risk.owner)}</p>` : ''}</article>`).join(''));
  } else {
    for (const kind of ['current','reuse','boundary','contract','decision','calculation','flow','rollout','risk']) {
      const entries=doc.entries.filter(entry=>entry.kind===kind);
      section(kind,t[kind],entries.map(entry=>`<article id="item-${escape(entry.id)}" class="technical-entry searchable"><div class="item-top"><span class="mono">${escape(entry.id)}</span>${entry.global ? badge('global',t) : ''}</div><h3>${escape(entry.title)}</h3>${prose(entry.body)}${['alternative','consequences','example'].map(key=>field(key,entry[key],t)).join('')}${entry.code ? `<pre><code>${escape(entry.code)}</code></pre>` : ''}${entry.diagram ? `<figure class="diagram">${diagrams[entry.id] || `<p class="notice">${t.sourceOnly}</p>`}${diagrams[entry.id] ? `<button class="diagram-copy" data-diagram-id="${escape(entry.id)}" type="button">${t.copyDiagram}</button>` : ''}<figcaption>${escape(entry.title)}</figcaption></figure><details><summary>${t.diagramSource}</summary><pre><code>${escape(entry.diagram)}</code></pre></details>` : ''}${entry.refs.length ? `<div class="item-links">${links(entry.refs)}</div>` : ''}</article>`).join(''));
    }
  }
  const gaps=coverageGaps(doc);
  if(gaps.length) section('coverage',t.coverage,`<div class="notice">${list(gaps)}</div>`);
  if(state) section('approvals',t.approvals,`<div class="approval-list">${['A','B','C'].map(gate=>`<div><span class="mono">Gate ${gate}</span>${state.approvals[gate] ? `<strong>${escape(state.approvals[gate].revision)}</strong>${prose(state.approvals[gate].evidence)}` : `<span class="muted">${t.draft}</span>`}</div>`).join('')}</div>`);
  const nav=sections.map((item,index)=>`<a href="#section-${item.id}"><span>${String(index+1).padStart(2,'0')}</span>${escape(item.title)}</a>`).join('');
  return `<a class="skip" href="#main">${t.skip}</a><aside class="sidebar"><div class="brand"><span class="brand-mark" aria-hidden="true">f.</span><span>Feature documents<small>${doc.kind==='prd'?'Product requirements':'Technical architecture'}</small></span></div><label class="search-label" for="search">${t.search}</label><input id="search" type="search" placeholder="${escape(t.search)}" autocomplete="off"><nav aria-label="${t.nav}">${nav}</nav><div class="sidebar-footer"><span class="mono">${escape(doc.id)}</span><span>${t.revision} ${escape(doc.revision)}</span></div></aside><div class="workspace"><div class="toolbar"><span class="toolbar-kind">${doc.kind==='prd'?'PRD':'TECH PLAN'}</span><div class="tools"><button id="expand">${t.expand}</button><button id="theme" aria-pressed="false">${t.theme}</button><button id="print">${t.print}</button><details class="file-menu"><summary>JSON</summary><div><label class="file-button" for="import">${t.import}</label><input type="file" id="import" accept=".json,application/json"><button id="export">${t.export}</button></div></details></div></div><main id="main" tabindex="-1"><header class="document-header"><div class="eyebrow">${t.source} <span> / </span> ${t.revision} ${escape(doc.revision)}</div><h1>${escape(doc.title)}</h1><p class="lead">${renderText(doc.summary)}</p><div class="document-meta">${badge(state?.approvals.C ? 'approved':'draft',t)}${doc.kind==='prd'?`<span>${doc.requirements.length} ${t.requirements.toLowerCase()} · ${doc.tasks.length} ${t.taskCount}</span>`:''}</div></header><p id="reader-status" role="status" aria-live="polite"></p><div id="sections">${sections.map(item=>item.html).join('')}</div><footer class="document-footer"><span>Feature documents · v1</span>${payload.specDigest?`<details><summary>${t.digest}</summary><code>${escape(payload.specDigest)}</code></details>`:''}</footer></main></div>`;
}
